var tableauQuestion = [
    {   question : "Freekill = ",
        propositionA : "Ban",
        propositionB : "Kick",
        propositionC : "Avertissement",
        propositionD : "Blâme",
        reponse : "A"},
    {   question : "Que veut dire «RP» ?",
        propositionA : "Rond-point",
        propositionB : "Role-play",
        propositionC : "Relation publique",
        propositionD : "Regle prioritaire",
        reponse : "B"},
    {   question : "On me braque avec une arme et je suis moi aussi armé :",
        propositionA : "Je sors mon arme et je menace mon agresseur",
        propositionB : "Je coopère et mets mes mains en l’air",
        propositionC : "Je m’enfuis",
        propositionD : "J’appelle la police",
        reponse : "B"},
    {   question : "Je me fais arrêter et je suis en route vers le commissariat. Il vaut mieux que je :",
        propositionA : "Préviennes un ami sur discord pour qu’il vienne me libérer",
        propositionB : "Tente de m’échapper par tous les moyens",
        propositionC : "M’explique auprès de la police",
        propositionD : "Fasse des gestes obscènes aux policiers",
        reponse : "C"},
    {   question : "Je suis pris en otage.",
        propositionA : "Pour passer le temps, je parle avec mes amis sur discord",
        propositionB : "Je préviens la police",
        propositionC : "J’essaye de sauver ma peau",
        propositionD : "Je reste dans mon coin et attends les instructions",
        reponse : "D"},
    {   question : "Pour savoir qui est dans un gang, je :",
        propositionA : "Me renseigne auprès des gangsters",
        propositionB : "Regarde les channels des gangs sur discord",
        propositionC : "Demande à un administrateur ou modérateur",
        propositionD : "Je prend quelqu’un en otage et lui demande",
        reponse : "A"},
    {   question : "Lors d’une action, un joueur me tue sans raison RP ",
        propositionA : "Je contacte immédiatement un administrateur",
        propositionB : "J’essaye de m’expliquer calmement avec la personne",
        propositionC : "Je me venge",
        propositionD : "Je place une prime sur sa tête",
        reponse : "B"},
    {   question : "Je viens de tuer quelqu’un, il me contacte pour des explications :",
        propositionA : "Je l’ignore",
        propositionB : "Je l’insulte",
        propositionC : "Je lui propose de s’expliquer sur discord",
        propositionD : "Je demande à un administrateur de régler le problème",
        reponse : "C"},
    {   question : "Je vois un flic en train d’arrêter quelqu’un :",
        propositionA : "Je n’y prête pas attention",
        propositionB : "Si je peux, j’essaye de rentrer dans son véhicule",
        propositionC : "Je nargue la personne arrêtée",
        propositionD : "Je tire sur le policier pour faire évader la personne interpelée",
        reponse : "A"},
    {   question : "Je suis en train de conduire, mon coffre rempli de marchandises illégales et soudain, un policier apparaît derrière moi :",
        propositionA : "Je lui cède le passage",
        propositionB : "Je m’enfuis ",
        propositionC : "Je continue ma route normalement",
        propositionD : "Je tire sur son véhicule",
        reponse : "A"},
    {   question : "Je me fais tuer au champ de cannabis ",
        propositionA : "Je retourne immédiatement au champ et continue ma récolte",
        propositionB : "Je prend le temps de m’équiper de nouveau et y retourne",
        propositionC : "Je n’ai pas le droit d’y retourner",
        propositionD : "J’appelle la police et indique la position du ou des criminel(s)",
        reponse : "B"},
    {   question : "Dans le cadre RP, je peux :",
        propositionA : "Divulguer gratuitement les infos de trafics illicites",
        propositionB : "Taper les gens dans la rue",
        propositionC : "Bloquer les entrées de bâtiments avec ma voiture",
        propositionD : "Manquer de respect aux flics et aux civils",
        reponse : "D"},
    {   question : "Dans la radio de la police, il y a 3 policiers connectés, j’ai le droit de :",
        propositionA : "Faire un braquage de banque",
        propositionB : "Faire des trajets de produits illicites",
        propositionC : "Faire une prise d’otages",
        propositionD : "Ecraser les autres joueurs",
        reponse : "B"},
    {   question : "En tant que dépanneur, je peux :",
        propositionA : "Coopérer avec les policiers ",
        propositionB : "Faire une prise d’otage",
        propositionC : "Faire des trajets de produits illicites",
        propositionD : "Posséder une arme à feu",
        reponse : "A"},
    {   question : "Quelqu’un se téléporte sur moi :",
        propositionA : "C’est obligatoirement un admin, il vient me crier dessus",
        propositionB : "C’est obligatoirement un admin, il fais son travail",
        propositionC : "C’est peut être un cheater, se faisant passer pour admin",
        propositionD : "C’est un admin, il abuse de ses pouvoirs en faisant ca",
        reponse : "B"},
]